version: "3.8"

services:
  # =============== BACKEND (PHP) ===============
  web:
    build: .
    ports:
      - "8000:80" # PHP backend di port 8000
    volumes:
      - ./:/var/www/html # Live reload untuk PHP
    depends_on:
      - db

  # =============== DATABASE ===============
  db:
    image: mysql:8.0
    ports:
      - "3306:3306" # MySQL di port 3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootoclock
      - MYSQL_DATABASE=oclockdb
      - MYSQL_USER=oclock_user
      - MYSQL_PASSWORD=oclock_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql-data:
